
CREATE TABLE IF NOT EXISTS lotes (id INTEGER PRIMARY KEY AUTOINCREMENT, numero INTEGER, fechaproduccion DATETIME)
CREATE TABLE IF NOT EXISTS productos (id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT, imagen BLOB)
CREATE TABLE IF NOT EXISTS lotes_productos (idlote INTEGER ,idproducto INTEGER )

